// <auto-generated />
using System;
using CoWildfireApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoWildfireApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.HasPostgresExtension("postgis");
            modelBuilder.HasPostgresExtension("uuid-ossp");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoWildfireApi.Models.FireEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AcresBurned")
                        .HasColumnType("numeric")
                        .HasColumnName("acres_burned");

                    b.Property<decimal?>("AvgDnbr")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_dnbr");

                    b.Property<Point>("Centroid")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("geometry")
                        .HasColumnName("centroid")
                        .HasAnnotation("Relational:ColumnOrder", 0)
                        .HasAnnotation("Relational:ComputedColumnSql", "ST_Centroid(perimeter)");

                    b.Property<string>("County")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("county");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("FireId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fire_id");

                    b.Property<string>("FireName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fire_name");

                    b.Property<decimal?>("MaxDnbr")
                        .HasColumnType("numeric")
                        .HasColumnName("max_dnbr");

                    b.Property<MultiPolygon>("Perimeter")
                        .HasColumnType("geometry")
                        .HasColumnName("perimeter");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("fire_events");
                });

            modelBuilder.Entity("CoWildfireApi.Models.FireEventH3Intersection", b =>
                {
                    b.Property<Guid>("FireEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("fire_event_id");

                    b.Property<long>("H3CellId")
                        .HasColumnType("bigint")
                        .HasColumnName("h3_cell_id");

                    b.Property<decimal?>("OverlapPct")
                        .HasColumnType("numeric")
                        .HasColumnName("overlap_pct");

                    b.HasKey("FireEventId", "H3CellId");

                    b.HasIndex("H3CellId");

                    b.ToTable("fire_event_h3_intersections");
                });

            modelBuilder.Entity("CoWildfireApi.Models.H3Cell", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AspectDegrees")
                        .HasColumnType("numeric")
                        .HasColumnName("aspect_degrees");

                    b.Property<decimal?>("AvgBurnSeverity")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_burn_severity");

                    b.Property<string>("BeetleKillPhase")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("beetle_kill_phase");

                    b.Property<decimal?>("BeetleKillSeverity")
                        .HasColumnType("numeric")
                        .HasColumnName("beetle_kill_severity");

                    b.Property<Polygon>("Boundary")
                        .HasColumnType("geometry")
                        .HasColumnName("boundary");

                    b.Property<decimal>("CenterLat")
                        .HasColumnType("numeric")
                        .HasColumnName("center_lat");

                    b.Property<decimal>("CenterLon")
                        .HasColumnType("numeric")
                        .HasColumnName("center_lon");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CurrentRiskScore")
                        .HasColumnType("numeric")
                        .HasColumnName("current_risk_score");

                    b.Property<short?>("DaysSinceRain")
                        .HasColumnType("smallint")
                        .HasColumnName("days_since_rain");

                    b.Property<decimal?>("DroughtIndex")
                        .HasColumnType("numeric")
                        .HasColumnName("drought_index");

                    b.Property<decimal?>("FuelMoisturePct")
                        .HasColumnType("numeric")
                        .HasColumnName("fuel_moisture_pct");

                    b.Property<short>("FiresLast20yr")
                        .HasColumnType("smallint")
                        .HasColumnName("fires_last_20yr");

                    b.Property<string>("H3Index")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("h3_index");

                    b.Property<short?>("LastFireYear")
                        .HasColumnType("smallint")
                        .HasColumnName("last_fire_year");

                    b.Property<string>("NoaaGridpointUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("noaa_gridpoint_url");

                    b.Property<decimal?>("RawsDistanceKm")
                        .HasColumnType("numeric")
                        .HasColumnName("raws_distance_km");

                    b.Property<decimal?>("RawsRelativeHumidityPct")
                        .HasColumnType("numeric")
                        .HasColumnName("raws_relative_humidity_pct");

                    b.Property<string>("RawsStationId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("raws_station_id");

                    b.Property<decimal?>("RawsWindSpeedMph")
                        .HasColumnType("numeric")
                        .HasColumnName("raws_wind_speed_mph");

                    b.Property<bool>("RedFlagWarning")
                        .HasColumnType("boolean")
                        .HasColumnName("red_flag_warning");

                    b.Property<decimal?>("RelativeHumidityPct")
                        .HasColumnType("numeric")
                        .HasColumnName("relative_humidity_pct");

                    b.Property<short>("Resolution")
                        .HasColumnType("smallint")
                        .HasColumnName("resolution");

                    b.Property<DateTimeOffset?>("RiskScoreUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("risk_score_updated_at");

                    b.Property<decimal?>("SlopeDegrees")
                        .HasColumnType("numeric")
                        .HasColumnName("slope_degrees");

                    b.Property<bool>("SmokeInferred")
                        .HasColumnType("boolean")
                        .HasColumnName("smoke_inferred");

                    b.Property<bool>("SmokePresent")
                        .HasColumnType("boolean")
                        .HasColumnName("smoke_present");

                    b.Property<decimal>("TotalAcresBurned")
                        .HasColumnType("numeric")
                        .HasColumnName("total_acres_burned");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VegetationType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vegetation_type");

                    b.Property<string>("WeatherSource")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("weather_source");

                    b.Property<decimal?>("WindSpeedMph")
                        .HasColumnType("numeric")
                        .HasColumnName("wind_speed_mph");

                    b.Property<short?>("YearsSinceLastFire")
                        .HasColumnType("smallint")
                        .HasColumnName("years_since_last_fire");

                    b.HasKey("Id");

                    b.ToTable("h3_cells");
                });

            modelBuilder.Entity("CoWildfireApi.Models.H3RiskHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("DroughtIndex")
                        .HasColumnType("numeric")
                        .HasColumnName("drought_index");

                    b.Property<decimal?>("FuelMoisturePct")
                        .HasColumnType("numeric")
                        .HasColumnName("fuel_moisture_pct");

                    b.Property<string>("H3Index")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("h3_index");

                    b.Property<decimal?>("RelativeHumidityPct")
                        .HasColumnType("numeric")
                        .HasColumnName("relative_humidity_pct");

                    b.Property<short>("Resolution")
                        .HasColumnType("smallint")
                        .HasColumnName("resolution");

                    b.Property<string>("RiskCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_category");

                    b.Property<decimal>("RiskScore")
                        .HasColumnType("numeric")
                        .HasColumnName("risk_score");

                    b.Property<DateTimeOffset>("ScoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scored_at");

                    b.Property<string>("WeatherSource")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("weather_source");

                    b.Property<decimal?>("WindSpeedMph")
                        .HasColumnType("numeric")
                        .HasColumnName("wind_speed_mph");

                    b.HasKey("Id");

                    b.HasIndex("ScoredAt");

                    b.HasIndex("H3Index", "ScoredAt");

                    b.ToTable("h3_risk_history");
                });

            modelBuilder.Entity("CoWildfireApi.Models.IngestionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("DatasetKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dataset_key");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("RecordsLoaded")
                        .HasColumnType("integer")
                        .HasColumnName("records_loaded");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("ingestion_log");
                });

            modelBuilder.Entity("CoWildfireApi.Models.FireEventH3Intersection", b =>
                {
                    b.HasOne("CoWildfireApi.Models.FireEvent", "FireEvent")
                        .WithMany("H3Intersections")
                        .HasForeignKey("FireEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoWildfireApi.Models.H3Cell", "H3Cell")
                        .WithMany("FireIntersections")
                        .HasForeignKey("H3CellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FireEvent");

                    b.Navigation("H3Cell");
                });

            modelBuilder.Entity("CoWildfireApi.Models.FireEvent", b =>
                {
                    b.Navigation("H3Intersections");
                });

            modelBuilder.Entity("CoWildfireApi.Models.H3Cell", b =>
                {
                    b.Navigation("FireIntersections");
                });
#pragma warning restore 612, 618
        }
    }
}
